from lib2to3.fixes.fix_input import context

def static_text(request):
    context = {
        'add_to_cart_with_plus': '+ Add To Cart',
        'add_to_cart':'add to cart',
        'add_to_wishlist':'add to wishlist',
        'add_to_compare': 'Add To Compare',
        'brand_text': 'Brand:',
        'category_text': 'Category:',
        'tags_text': 'Tags:',
        'product_text': 'Product',
        'description_text': 'Description',
        'additional_info_text': 'Additional information',
        'product_info_text': 'Product Information',
        'home_text': 'Home',
        'shop_text': 'Shop',
        'shopping_cart_text':'Shopping Cart',
        'product_details_text': 'Product Details',
        'related_products_text': 'Related Products',
        'sale_text': 'Sale',
        'new_text': 'New',
        'size_text': 'Size:',
        'colors_text': 'Colors:',
        'sort_by_price': 'Sort by Price',
        'low_to_high': 'Low to High',
        'showing': 'Showing',
        'of': 'of',
        'results': 'results',
        'no_product_available': 'No products available',
        'points': '...',
        'butterfly_shop': 'Butterfly Shop',
        'sign_out': 'Sign Out',
        'sign_in':'Sign In',
        'register':'Register',
        'contacts_text': 'Contacts',
        'filter_categories': 'Categories',
        'filter_branding': 'Branding',
        'filter_colors': 'Colors',
        'filter_tags': 'Tags',
        'filter_size': 'Size',
        'filter_price': 'Filter Price',
        'price_filter_1': 'UAH 0.00 - UAH 500.00',
        'price_filter_2': 'UAH 500.00 - UAH 1000.00',
        'price_filter_3': 'UAH 1000.00 - UAH 1500.00',
        'price_filter_4': 'UAH 1500.00 - UAH 2000.00',
        'price_filter_5': 'UAH 2000.00 - UAH 2500.00',
        'price_filter_6': 'UAH 2500.00+',
        'filter_price_option_right_1': 'UAH 0 - UAH 550.00',
        'filter_price_option_right_2': 'UAH 550.00 - UAH 1000.00',
        'clear_filters': 'Clear Filters',
        'quantity_text': 'Quantity',
        'total_text': 'Total',
        'proceed_to_checkout_text':'Proceed to checkout',
        'continue_shopping_text':'Continue Shopping',
        'update_cart_text':'Update Cart',
        'cart_total_text':'Cart total',
        'billing_details_text':'Billing Details',
        'create_an_account':'Create an Account?',
        'create_account_msg': 'Create an account by entering the information below. If you are a returning customer '
                              'please login at the top of the page',
        'account_password': 'Account Password',
        'checkbox_notes_msg':'Note about your order, e.g, special noe for delivery',
        'your_order_text':'Your order',
        'place_order': 'PLACE ORDER',
        'return_to_shop': 'Return to Shop',
        'thx_order_text':'Thank You for Your Order!',
        'confirm_manager': 'Our manager will contact you soon to confirm the details of your order.',
        'information': 'Information',
        'contact_us': 'Contact Us',
        'collection': 'Collection',
        'new_arrivals':'New Arrivals',
        'hot_sales': 'Hot Sales'
    }

    return {
        'static_text': context
    }