# Generated by Django 5.1.2 on 2024-10-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_is_liked_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
